[package]
name = "hook"
version = "0.1.0"
edition = "2021"

[dependencies]
retour = { version = "0.3.1", features = ["static-detour"] }
windows = { version = "0.56.0", features = ["Win32_System_SystemServices", "Win32_System_LibraryLoader"]}

[lib]
crate-type = ["cdylib"]